.PHONY: help install uninstall install-nvim install-tmux install-bash install-git install-lazygit install-karabiner \
        uninstall-nvim uninstall-tmux uninstall-bash uninstall-git uninstall-lazygit uninstall-karabiner \
        check-stow list clean

.DEFAULT_GOAL := help

# Package directory for stow
PACKAGES_DIR := packages
STOW := stow
STOW_FLAGS := --verbose --target=$(HOME) --dir=$(PACKAGES_DIR)

## help: Show this help message
help:
	@echo "Dotfiles Management"
	@echo ""
	@echo "Usage: make [target]"
	@echo ""
	@echo "Available targets:"
	@awk 'BEGIN {FS = ":.*##"; printf ""} \
		/^[a-zA-Z_-]+:.*##/ { printf "  \033[36m%-20s\033[0m %s\n", $$1, $$2 } \
		/^##/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 4) }' $(MAKEFILE_LIST)
	@echo ""

check-stow: ## Check if GNU stow is installed
	@command -v stow >/dev/null 2>&1 || { echo >&2 "GNU stow is not installed. Install it with 'brew install stow' or 'apt install stow'"; exit 1; }
	@echo "GNU stow is installed: $$(stow --version | head -n1)"

## Installation targets:
install: check-stow ## Install all dotfiles
	@echo "Installing all dotfiles..."
	@$(MAKE) install-nvim
	@$(MAKE) install-tmux
	@$(MAKE) install-bash
	@$(MAKE) install-git
	@$(MAKE) install-lazygit
	@$(MAKE) install-karabiner
	@echo ""
	@echo "Installation complete!"
	@echo ""
	@echo "Note: Bash scripts need to be sourced in your ~/.bashrc or ~/.zshrc"
	@echo "      Add the following lines:"
	@echo ""
	@echo "  source ~/.local/share/bash-scripts/bash/show_git_branch.sh"
	@echo "  source ~/.local/share/bash-scripts/bash/cd_with_fzf.sh"
	@echo "  source ~/.local/share/bash-scripts/bash/cd_git_worktree.sh"
	@echo "  source ~/.local/share/bash-scripts/bash/ssh_config_with_fzf.sh"
	@echo "  source ~/.local/share/bash-scripts/bash/tmux_autologging_ssh.sh"
	@echo "  source ~/.local/share/bash-scripts/bash/tmux_with_logging.sh"
	@echo ""

install-nvim: check-stow ## Install NeoVim configuration
	@echo "Installing NeoVim config with stow..."
	cd $(PWD) && $(STOW) $(STOW_FLAGS) nvim

install-tmux: check-stow ## Install tmux configuration
	@echo "Installing tmux config with stow..."
	cd $(PWD) && $(STOW) $(STOW_FLAGS) tmux

install-bash: check-stow ## Install bash/zsh scripts
	@echo "Installing bash scripts with stow..."
	cd $(PWD) && $(STOW) $(STOW_FLAGS) bash

install-git: check-stow ## Install git configuration
	@echo "Installing git config with stow..."
	cd $(PWD) && $(STOW) $(STOW_FLAGS) git

install-lazygit: check-stow ## Install lazygit configuration (macOS/Linux)
	@echo "Installing lazygit config with stow..."
	@if [ "$$(uname)" = "Darwin" ]; then \
		cd $(PWD) && $(STOW) $(STOW_FLAGS) lazygit-macos; \
		echo "Lazygit config installed (macOS)"; \
	else \
		cd $(PWD) && $(STOW) $(STOW_FLAGS) lazygit-linux; \
		echo "Lazygit config installed (Linux)"; \
	fi

install-karabiner: check-stow ## Install Karabiner-Elements config (macOS only)
	@echo "Installing Karabiner-Elements config with stow..."
	@if [ "$$(uname)" = "Darwin" ]; then \
		cd $(PWD) && $(STOW) $(STOW_FLAGS) karabiner; \
		echo "Karabiner config installed"; \
	else \
		echo "Karabiner is macOS only, skipping..."; \
	fi

## Uninstallation targets:
uninstall: check-stow ## Uninstall all dotfiles
	@echo "Uninstalling all dotfiles..."
	@-$(MAKE) uninstall-nvim
	@-$(MAKE) uninstall-tmux
	@-$(MAKE) uninstall-bash
	@-$(MAKE) uninstall-git
	@-$(MAKE) uninstall-lazygit
	@-$(MAKE) uninstall-karabiner
	@echo "Uninstall complete!"

uninstall-nvim: ## Uninstall NeoVim configuration
	@echo "Uninstalling NeoVim config with stow..."
	cd $(PWD) && $(STOW) --delete $(STOW_FLAGS) nvim

uninstall-tmux: ## Uninstall tmux configuration
	@echo "Uninstalling tmux config with stow..."
	cd $(PWD) && $(STOW) --delete $(STOW_FLAGS) tmux

uninstall-bash: ## Uninstall bash/zsh scripts
	@echo "Uninstalling bash scripts with stow..."
	cd $(PWD) && $(STOW) --delete $(STOW_FLAGS) bash

uninstall-git: ## Uninstall git configuration
	@echo "Uninstalling git config with stow..."
	cd $(PWD) && $(STOW) --delete $(STOW_FLAGS) git

uninstall-lazygit: ## Uninstall lazygit configuration
	@echo "Uninstalling lazygit config with stow..."
	@if [ "$$(uname)" = "Darwin" ]; then \
		cd $(PWD) && $(STOW) --delete $(STOW_FLAGS) lazygit-macos; \
	else \
		cd $(PWD) && $(STOW) --delete $(STOW_FLAGS) lazygit-linux; \
	fi

uninstall-karabiner: ## Uninstall Karabiner-Elements configuration
	@echo "Uninstalling Karabiner config with stow..."
	@if [ "$$(uname)" = "Darwin" ]; then \
		cd $(PWD) && $(STOW) --delete $(STOW_FLAGS) karabiner; \
	fi

clean: ## Clean up autogenerated files
	@echo "Cleaning up autogenerated files..."
	@find . -name "_autogenerated_*.vim" -type f -delete
	@echo "Clean complete"
