@echo off
cd /d %~dp0

set CUR_PATH=%~dp0
set VIM_PLUG_PATH=%HOMEPATH%\AppData\Local\nvim-data\site\autoload\plug.vim
echo %VIM_PLUG_PATH%

openfiles > NUL 2>&1
if NOT %ERRORLEVEL% EQU 0 goto NotAdmin

rem Install vim-plug if not exist plugin file.
if exist %VIM_PLUG_PATH% (goto SkipVimPlugInstall)
echo Install vim_plug (Plugin Manager)
powershell -NoProfile -ExecutionPolicy Unrestricted .\installscript\install_vim-plug_for_neovim_windows.ps1
:SkipVimPlugInstall

rem generate launcher script
(
echo.set runtimepath+=%CUR_PATH%NeoVim\
echo.if filereadable(expand('%CUR_PATH%NeoVim\init.vim'^)^)
echo.  echom 'Load init'
echo.  source %CUR_PATH%NeoVim\init.vim
echo.else
echo.  echom 'Can not load init'
echo.endif
)>NeoVim\_autogenerated_launcher.vim

md %HOMEPATH%"\AppData\Local\nvim\"
mklink %HOMEPATH%"\AppData\Local\nvim\init.vim" %~dp0"NeoVim\_autogenerated_launcher.vim"

echo Complete
nvim-qt "+:messages" %CUR_PATH%setup_complete.txt

goto EOF

:NotAdmin
echo Administrator privileges required
powershell start-process setup_neovim_windows.bat -verb runas
goto EOF

:End
pause
:EOF
